import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/provider/queryProvider";
import { AppThemeProvider } from "@/components/provider/ThemeProvider";
import { LenisProvider } from "@/utils/Lenis";
import Layout from "@/components/Layout/Applayout";
import SessionClientProvider from "@/components/provider/Sessionprovider";
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuickBill",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionClientProvider>
          <LenisProvider>
            <AppThemeProvider>
             <Providers>
                <UserProvider> {/* <-- wrap here */}
                  <Layout>{children}</Layout>
                </UserProvider>
              </Providers>
            </AppThemeProvider>
          </LenisProvider>
        </SessionClientProvider>
      </body>
    </html>
  );
}
